### ISSUE TITLE
How to download data from the NDA

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/cdni-brain#132]
Instructions are provided here: https://nda.nih.gov/ndarpublicweb/Documents/Accessing+Shared+Data+Sept_2021-1.pdf
This PDF includes instructions on how to create an account, obtaining access to the data, generating a package to download, and using their download manager

Here are more detailed instructions for when you are ready to query and generate a package to download:
1 - after logging into the NDA, follow this [Get Data](https://nda.nih.gov/general-query.html?q=query=collections%20~and~%20orderBy=id%20~and~%20orderDirection=Ascending) link to the NDA Query Tool

2 - Then go to page 11 of the PDF and follow the instructions. Note: the simplest waqy to search for a repository is to enter the collection ID under Text Search

Additional tip: The NDA website is very slow, so when you're at the Data Packaging Page (page 13 of PDF), each time you check or uncheck any box for each individual Collection/upload submission in the left-hand panel or Data Structure Category in the right-hand panel, it takes a few seconds to think. So remember to use the "Select/Deselect All" option in the upper right-hand corner of each panel to your advantage 

This is a fairly straightforward and quick process once your access to the data collection is approved. The download packages also build fairly quickly - I created a package with 1 TB of data and I think it finished creating the package in under 10 minutes.

The lab has also developed a utility specifically for ABCC downloads here: https://github.com/DCAN-Labs/nda-abcd-s3-downloader, but it is currently under construction and not working

**Comment by audreymhoughton** [comment]
@LuciMoore I believe the downloader is broken at this time - there are open GitHub issues assigned to various team members that need to be done in order for it to be operational. I think the downloader's instructions will need to be adjusted as a result. (Just FYI)

**Comment by LuciMoore** [comment]
@audreymhoughton I wrote out these instructions because I was downloading stuff already, so it worked for me. anyway I'm about to try it again, so will update you. I might be totally missing something here though, so let's touch base if needed!

**Comment by LuciMoore** [comment]
@audreymhoughton I edited my post to clarify that the downloader isn't working currently

**Comment by audreymhoughton** [comment]
noting that we should describe both methods of downloading (with and without the s3 downloader)

for without, see the s3 downloader's readme.
