### ISSUE TITLE
dead internal link in miniconda.md

### ISSUE THREAD

**Issue by tikal004** [DCAN-Labs/cdni-brain#146]
The `miniconda.md`  file has a relative link to `(#9-dicom-to-bids-conversion-dcm2bids)`.
This links to a header in the same page that does not exist.

Where should this be linked? This page only has one header. Should this link to a different page?

**Comment by rosemccollum** [comment]
Ahh yea this is leftover from when it was a google doc, it should link to https://dcan-labs-informational-guide.readthedocs.io/en/latest/dcm2bids/

**Comment by tikal004** [comment]
#151 addressed this
