### ISSUE TITLE
NGDR transfer permissions

### ISSUE THREAD

**Issue by lundq163** [DCAN-Labs/cdni-brain#195]
Add in what the correct permissions should be, i.e. group rwx, user rw (i think those are the right ones but i could be mistaken)

**Comment by audreymhoughton** [comment]
@lundq163 the permissions and owners of the files is something that is constantly changing on MSI - I think it's user rx - the only they we are not allowed to do is write

- will look into this before updating doc

**Comment by LuciMoore** [comment]
@lundq163 I don't think this is relevant anymore, but let me know if you think otherwise! closing for now
