### ISSUE TITLE
add info about where phenotypic data is stored 

### ISSUE THREAD

**Issue by rosemccollum** [DCAN-Labs/cdni-brain#225]
ie rando149/Collection_31651_Supporting_Documentation/ for ABCD data

**Comment by LuciMoore** [comment]
@rosemccollum I already started this in the[ Data Repositories Info spreadsheet](https://docs.google.com/spreadsheets/d/1nqZ18lFvSf5K7eh91Xp2V-ouBoFWHorNDbW6WSxP1so/edit?usp=sharing). it's incomplete, so I haven't shared it widely, but I think it might be good to go ahead and share it anyway at this point and people can help build on it

perhaps we could start a Data Repositories section for the Brain and include a link to it there?

**Comment by LuciMoore** [comment]
will be resolved as part of separate issue posted: https://github.com/DCAN-Labs/cdni-brain/issues/254
